main: net.arcticforestmc.SlimePuncher.SlimePuncher
name: "SlimePuncher"
version: 0.0.0-ALPHA
authors: ["Connor Michalec", "Valdemar Foster"]
commands:
  testdingdong:
  bits:
    description: Gets the amount of bits the player has.

  mobsAlive:
    description: Gets the amount of zombies alive.
depends: ["WorldEdit", "ProtocolLib"]
