main: net.arcticforestmc.SlimePuncher.SlimePuncher
name: "SlimePuncher"
version: 0.0.0-ALPHA
authors: ["Connor Michalec", "Valdemar Foster"]
commands:
  testdingdong:
  test:
    description: Gets the amount of bits the player has.
  disablegameplayer:
  enablegameplayer:
  setmobsalive:

  mobsAlive:
    description: Gets the amount of zombies alive.
depend: ["WorldEdit", "ProtocolLib", "ArcitcStatsAPI"]

softdepend: [HolographicDisplays]
